Feature #4 new custom script for DDI dataset
ExploreASL/CustomScripts pull request #5
Opened 2021-04-23 09:47 UTC by BeatrizPadrela

Check issue #4 for more information
The DDI data is now sorted in the DDI folder, in the format: scanners / sourcedata

2021-04-23 11:38 UTC, jan-petr requested changes
Perfect - two small things - you should be able to see them among the other comments in the PR. And also inside the code in the 'Files changed' tab of the PR.

2021-04-23 11:38 UTC, jan-petr commented on DDI/DDI_CustomSortingScript.m
> +Odir = '/home/bestevespadrela/lood_storage/divi/Projects/ExploreASL/DDI/ASL_dicoms';
Minor change - can you please take the base path 
`/home/bestevespadrela/lood_storage/divi/Projects/ExploreASL/DDI`
and put it to a separate variable at the start of the script?

And then use this to create Odir, Ddir, T1dir, FLAIRdir, root so that it is easier to change these.

In general, it is fine to have hard-coded values in the CustomScripts, we aim only for the basic configurability.

2021-04-23 11:38 UTC, jan-petr commented on DDI/DDI_CustomSortingScript.m~
> +%% Custom Sorting script - DDI data
Please remove this m~ file. Thanks

2021-04-26 07:16 UTC, MichaelStritt commented on DDI/DDI_CustomSortingScript.m
> +Odir = '/home/bestevespadrela/lood_storage/divi/Projects/ExploreASL/DDI/ASL_dicoms';
Should be fixed in 6be50cd

2021-04-26 07:16 UTC, MichaelStritt commented on DDI/DDI_CustomSortingScript.m~
> +%% Custom Sorting script - DDI data
Should be fixed in 6be50cd.

2021-04-26 07:27 UTC, MichaelStritt approved these changes
The changes that Jan asked for are there 👍

2021-04-26 09:39 UTC, jan-petr approved these changes
OK

2021-04-26 10:53 UTC, merged